-- PEN_LIST 테이블 생성 => 제조회사(COMPANY), 색상(COLOR)
-- PEN_LIST 테이블 출력
CREATE TABLE PEN_LIST(
    COMPANY VARCHAR(15),
    COLOR VARCHAR(15)
);
SELECT * FROM PEN_LIST;
COMMIT;

-- PEN_LIST 테이블명 PEN으로 변경   -> ALTER(RENAME)
ALTER TABLE PEN_LIST RENAME TO PEN;
-- PEN 테이블 중 COMPANY 칼럼명 COM으로 변경   -> ALTER(RENAME COLUMN)
ALTER TABLE PEN RENAME COLUMN COMPANY TO COM;
-- PEN 테이블에 굵기(THICKNESS) 칼럼 추가     -> ALTER(ADD)
ALTER TABLE PEN ADD THICKNESS FLOAT;
-- PEN 테이블에 가격(PRICE) 칼럼 추가         -> ALTER(ADD)
ALTER TABLE PEN ADD PRICE INT;
-- PEN 테이블 출력
SELECT * FROM PEN;
COMMIT;

-- PEN 테이블에 대해 데이터 5-10개 삽입     -> INSERT
INSERT INTO PEN VALUES('모나미', 'BLACK', 0.5, 1700);
INSERT INTO PEN VALUES('제트스트림', 'RED', 0.7, 2500);
INSERT INTO PEN VALUES('자바', 'BLUE', 0.35, 2000);
INSERT INTO PEN VALUES('몽블랑', 'BLACK', 0.5, 2000);
INSERT INTO PEN VALUES('제트스트림', 'BLUE', 0.5, 3000);
-- PEN 테이블 전체 데이터 출력
SELECT * FROM PEN;
COMMIT;

-- PEN 데이터 중, 가격이 2000원 이상인 데이터의 제조회사를 모두 '모나미'로 변경
--      -> UPDATE 통해서, 조건 걸어주고 데이터 변경
UPDATE PEN SET COM='모나미' WHERE PRICE>=2000;
-- PEN 데이터 중, 굵기가 0.5인 데이터의 가격을 1500으로 변경
UPDATE PEN SET PRICE=1500 WHERE THICKNESS=0.5;
-- PEN 테이블 전체 데이터 출력
SELECT * FROM PEN;

-- PEN 테이블 중 굵기, 색상 칼럼 데이터만 출력
SELECT THICKNESS, COLOR FROM PEN;
-- PEN 데이터 중, 색상이 'BLACK'인 데이터의 색상, 굵기, 가격 칼럼 데이터만 출력
SELECT COLOR, THICKNESS, PRICE FROM PEN WHERE COLOR='BLACK';
COMMIT;

-- PEN 테이블의 모든 데이터 삭제   -> TRUNCATE
TRUNCATE TABLE PEN;
-- PEN 테이블 전체 출력
SELECT * FROM PEN;
-- PEN 테이블 전체 삭제        -> DROP
DROP TABLE PEN;