DROP TABLE KBSTUDENT;

CREATE TABLE KBSTUDENT(
HAKBEON VARCHAR2(10) PRIMARY KEY,
NAME VARCHAR2(100),
HAKGWA_CODE CHAR(3)
);

INSERT INTO KBSTUDENT VALUES('1', '이동준','001');
INSERT INTO KBSTUDENT(NAME, HAKGWA_CODE, HAKBEON) VALUES ('유지웅','002','2');
INSERT INTO KBSTUDENT(HAKBEON, HAKGWA_CODE) VALUES('3','003'); --이름을 생략해 봄

SELECT * FROM KBSTUDENT;

UPDATE KBSTUDENT SET NAME='이유나' WHERE HAKBEON='3'; --나중에 UPDATE문으로 이름을 추가함



SELECT * FROM DJSTUDENT;
SELECT * FROM KBMAJOR;
SELECT * FROM KBSTUDENT; --외래키를 추가함. 참고할 테이블은 KBMAJOR의 CODE

-- 전공테이블의 CODE를 "참조"하여서 학생 테이블의 데이터를 관리하겠다는 의미
-- 전공테이블에 없는 전공은 추가할 수가 없다.
ALTER TABLE KBSTUDENT ADD CONSTRAINT FK_CODE FOREIGN KEY(HAKGWA_CODE) REFERENCES KBMAJOR(CODE);

INSERT INTO KBSTUDENT VALUES('4', '정용억', '001'); --OK
INSERT INTO KBSTUDENT VALUES('5', '홍주환', '111'); --학과코드가 111인 과는 현재 없는 상태

INSERT INTO KBMAJOR VALUES('004', '경영');
INSERT INTO KBSTUDENT VALUES('5', '권병진', '004');


--JOIN
-- 두 개 이상의 테이블을 공통된 열(COLUMN)로 묶는다.
SELECT HAKBEON, KBSTUDENT.NAME, KBMAJOR.NAME FROM KBSTUDENT JOIN KBMAJOR 
ON kbstudent.hakgwa_code=KBMAJOR.CODE;

SELECT HAKBEON 학번, KBSTUDENT.NAME 학생이름, KBMAJOR.NAME 학과명 
FROM KBSTUDENT JOIN KBMAJOR 
ON kbstudent.hakgwa_code=KBMAJOR.CODE;

-- WHERE을 이용한 JOIN문, 두 테이블을 콤마(,)로 묶고, WHERE문을 사용함
SELECT HAKBEON 학번, KBSTUDENT.NAME 학생이름, KBMAJOR.NAME 학과명 
FROM KBSTUDENT, KBMAJOR 
WHERE kbstudent.hakgwa_code=KBMAJOR.CODE;



