-- EMPLOYEE 테이블의 데이터 추가 수행하는 프로시저 선언
CREATE OR REPLACE PROCEDURE ADD_EMPLO
(
    INPUT_NUM IN VARCHAR2,
    INPUT_NAME IN VARCHAR2,
    INPUT_AGE IN INT,
    INPUT_DEPART IN VARCHAR2
)
IS BEGIN
    INSERT INTO EMPLOYEE VALUES(INPUT_NUM, INPUT_NAME, INPUT_AGE, INPUT_DEPART);
END ADD_EMPLO;