-- 트리거
-- insert 할 때 마다 bookstorelog에 데이터 추가
CREATE OR REPLACE TRIGGER TR_BOOKSTORE
BEFORE INSERT ON BOOK
FOR EACH ROW
    BEGIN 
    IF INSERTING THEN
        INSERT INTO BOOKSTORELOG(NUM,BOOKNAME)
        VALUES (BOOKLOG.NEXTVAL,:NEW.BOOKNAME);
    END IF;
END TR_BOOKSTORE;